-- 1. Create the table
CREATE TABLE IF NOT EXISTS codigos_postales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_postal TEXT NOT NULL,
    estado TEXT,
    municipio TEXT,
    colonia TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Add an index for faster searching by CP
CREATE INDEX IF NOT EXISTS idx_cp_search ON codigos_postales (codigo_postal);

-- 3. Add an index for state/municipality if needed
CREATE INDEX IF NOT EXISTS idx_cp_state_mun ON codigos_postales (estado, municipio);

-- 4. Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE codigos_postales ENABLE ROW LEVEL SECURITY;

-- 5. Policy to allow everyone to SELECT (read) zip codes
CREATE POLICY "Allow public read access" ON codigos_postales
    FOR SELECT USING (true);

-- 6. Policy to allow authenticated users to INSERT (for the import tool)
CREATE POLICY "Allow authenticated inserts" ON codigos_postales
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 7. Policy to allow authenticated users to UPDATE (if needed)
CREATE POLICY "Allow authenticated updates" ON codigos_postales
    FOR UPDATE USING (auth.role() = 'authenticated');
